<?php
// Load translation data
$this->i18nTheme('main');
// Load jQuerty
$this->jQuery();
// Load Bootstrap css by Twitter Team
$this->bootstrap(array(
    'js/bootstrap.min.js',
    'css/font-awesome.min.css',
));
// Load css
$this->css(array(
    $this->assetTheme('css/style.css'),
    $this->assetLocale('rtl.css'),
));
// Load js
$this->js($this->assetTheme('js/top-block.js'));

// Load navigation
$navigation = $this->nav('front');

// Load Block
$blocks = $this->blocks();
$blockTemplate = $this->template('block');

?>
<!DOCTYPE HTML>
<html lang="<?php echo $locale; ?>">
	<head>
		<meta charset="<?php echo $charset; ?>">
		<?php echo $this->assemble('headTitle', 4); ?>
		<?php echo $this->assemble('headMeta', 4); ?>
		<?php echo $this->assemble('headLink', 4); ?>
		<?php echo $this->assemble('headStyle', 4); ?>
	</head>
	<body id="pi-module-<?php echo Pi::service('module')->current(); ?>" class="<?php echo $locale; ?>">
		<!-- Start Header -->
		<header id="pi-header">
			<div id="pi-header-top" class="container">
				<div class="row">
					<div class="span12" id="pi-header-title">
						<hgroup id="pi-header-title-text">
							<h1><a href="<?php echo Pi::url('www'); ?>" title="<?php echo $this->escape($sitename); ?>"><?php echo $this->escape($sitename); ?></a></h1>
							<h2><?php echo $this->escape($slogan); ?></h2>
						</hgroup>
					</div>
				</div>
			</div>
			<?php if ($navigation) { ?>
			<nav id="pi-header-nav" class="navbar navbar-inverse navbar-static-top">
				<div class="navbar-inner">
					<div class="container">
						<div class="row">
							<?php echo $navigation->menu()->setUlClass('nav'); ?>
						</div>  
					</div>
				</div>
			</nav>
			<?php } ?>
			<div id="pi-header-banner"></div>
		</header>
		<!-- Start Content -->
		<section id="pi-canvas">
			<div id="pi-canvas-content" class="container">
				<?php if ($navigation) { ?>
				<?php $breadcrumbs = $navigation->breadcrumbs()->setSeparator('<span class="divider">&gt;</span>')->render(); ?>
				<?php if ($breadcrumbs) { ?>
				<!-- Global breadcrumbs starts -->
				<div class="breadcrumb">
					<?php echo $breadcrumbs; ?>
				</div>
                <!-- Global breadcrumbs ends -->
				<?php } ?>
				<?php } ?>
<!-- Top head zone -->
        <?php if (!empty($blocks['0'])) { ?>
        <div class="pi-zone-0">
            <?php foreach ($blocks['0'] as $block) {
                include $blockTemplate;
            } ?>
        </div>
        <?php } ?>
        <!-- Left zone -->
        <?php if (!empty($blocks['1'])) { ?>
        <div class="pi-zone-1">
            <?php foreach ($blocks['1'] as $block) {
                include $blockTemplate;
            } ?>
        </div>
        <?php } ?>
        <!-- Right zone -->
        <?php if (!empty($blocks['8'])) { ?>
        <div class="pi-zone-8">
            <?php foreach ($blocks['8'] as $block) {
                include $blockTemplate;
            } ?>
        </div>
        <?php } ?>
        <div class="pi-main<?php 
        if (!empty($blocks['1'])) { echo ' pi-main-left'; }
        if (!empty($blocks['8'])) { echo ' pi-main-right'; }
        ?>">
            <!-- Center top zone -->
            <?php if (!empty($blocks['2'])) { ?>
            <div class="pi-zone-2">
                <?php foreach ($blocks['2'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
            <?php } ?>
            <!-- Top left zone -->
            <?php if (!empty($blocks['3'])) { ?>
            <div class="pi-zone-3">
                <div class="pi-zone-inner">
                    <?php foreach ($blocks['3'] as $block) {
                        include $blockTemplate;
                    } ?>
                </div>
            </div>
            <?php } ?>
            <!-- Top right zone -->
            <?php if (!empty($blocks['4'])) { ?>
            <div class="pi-zone-4">
                <?php foreach ($blocks['4'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
            <?php } ?>
            <!-- Module zone -->
            <div class="row-fluid pi-module-content">
                <?php echo $content; ?>
            </div>
            <!-- Bottom left zone -->
            <?php if (!empty($blocks['5'])) { ?>
            <div class="pi-zone-5">
                <?php foreach ($blocks['5'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
            <?php } ?>
            <!-- Bottom right zone -->
            <?php if (!empty($blocks['6'])) { ?>
            <div class="pi-zone-6">
                <?php foreach ($blocks['6'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
            <?php } ?>
            <!-- Center bottom zone -->
            <?php if (!empty($blocks['7'])) { ?>
            <div class="pi-zone-7">
                <?php foreach ($blocks['7'] as $block) {
                    include $blockTemplate;
                } ?>
            </div>
            <?php } ?>
        </div>
        <!-- Bottom foot zone -->
        <?php if (!empty($blocks['99'])) { ?>
        <div class="pi-zone-99">
            <?php foreach ($blocks['99'] as $block) {
                include $blockTemplate;
            } ?>
        </div>
        <?php } ?>
			</div>
		</section>
		<!-- Start Footer -->
		<footer id="pi-footer">
			<div id="pi-footer-bar-1">
				<div class="container">
					<div id="pi-footer-box" class="row">
						<div class="span3">
							<h3><i class="icon-paper-clip"></i> Footer title</h3>
							<ul>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
							</ul>
						</div>
						<div class="span3">
							<h3><i class="icon-paper-clip"></i> Footer title</h3>
							<ul>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
							</ul>
						</div>
						<div class="span3">
							<h3><i class="icon-paper-clip"></i> Footer title</h3>
							<ul>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
							</ul>
						</div>
						<div class="span3">
							<h3><i class="icon-paper-clip"></i> Footer title</h3>
							<ul>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
								<li><a title="text text text" href="#"><i class="icon-angle-right"></i> test test test</a></li>
							</ul>
						</div>		   
					</div>
				</div>
			</div>
			<div id="pi-footer-bar-2">
				<div class="container">
					<div class="row">
						<div class="span12">
							<div id="pi-footer-copyright">
								<a href="<?php echo Pi::url('www'); ?>" title="<?php echo $this->escape($sitename); ?>">&copy;<?php echo $this->escape($sitename); ?></a><span class="pi-divider">|</span>
								<a href="http://www.pialog.org" title="Pi Engine" target="_blank">Powered by Pi Engine</a><span class="pi-divider">|</span>
								<a href="http://www.pialog.org" title="Pi Engine" target="_blank">Design of Pi Engine</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</footer>
		<?php echo $this->assemble('headScript', 4); ?>
		<?php echo $this->assemble('footScript', 4); ?>
	</body>
</html>